// Voca 단어 데이터베이스 - DAY별 50개씩, 각 시험 수준에 맞게 구성 (무작위 배열)
// TOEFL: 학술적 영어 (대학 수준)
// SAT: 고급 어휘 (대학 입학 시험)
// IELTS: 일상+학술 영어 (영국식)
// TOEIC: 비즈니스 영어 (직장)
// ACT: 대학 진학 기본 (미국)

// 무작위 배열을 위한 Fisher-Yates 셔플 함수
function shuffleArray<T>(array: T[]): T[] {
  const newArray = [...array];
  for (let i = newArray.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
  }
  return newArray;
}

// TOEFL 학술 단어 풀 (무작위로 섞임)
const TOEFL_WORDS_POOL = shuffleArray([
  { english: "abstract", korean: "추상적인", synonyms: "theoretical, conceptual, intangible" },
  { english: "accumulate", korean: "축적하다", synonyms: "gather, collect, amass" },
  { english: "adjacent", korean: "인접한", synonyms: "neighboring, adjoining, nearby" },
  { english: "advocate", korean: "옹호하다", synonyms: "support, promote, champion" },
  { english: "aggregate", korean: "집합체", synonyms: "total, whole, sum" },
  { english: "allocate", korean: "할당하다", synonyms: "distribute, assign, allot" },
  { english: "ambiguous", korean: "모호한", synonyms: "unclear, vague, uncertain" },
  { english: "anticipate", korean: "예상하다", synonyms: "expect, foresee, predict" },
  { english: "apparent", korean: "명백한", synonyms: "obvious, evident, clear" },
  { english: "arbitrary", korean: "임의의", synonyms: "random, capricious, subjective" },
  { english: "behalf", korean: "대신하여", synonyms: "representation, interest, sake" },
  { english: "bias", korean: "편견", synonyms: "prejudice, partiality, favoritism" },
  { english: "bulk", korean: "대량", synonyms: "mass, volume, majority" },
  { english: "capable", korean: "유능한", synonyms: "able, competent, qualified" },
  { english: "category", korean: "범주", synonyms: "class, type, group" },
  { english: "cease", korean: "중단하다", synonyms: "stop, end, halt" },
  { english: "channel", korean: "경로", synonyms: "route, medium, path" },
  { english: "clarify", korean: "명확히 하다", synonyms: "explain, elucidate, clear" },
  { english: "coherent", korean: "일관된", synonyms: "logical, consistent, rational" },
  { english: "coincide", korean: "일치하다", synonyms: "correspond, match, align" },
  { english: "collapse", korean: "붕괴하다", synonyms: "fall, crumble, breakdown" },
  { english: "colleague", korean: "동료", synonyms: "coworker, associate, peer" },
  { english: "commence", korean: "시작하다", synonyms: "begin, start, initiate" },
  { english: "comment", korean: "논평", synonyms: "remark, observation, statement" },
  { english: "commission", korean: "위원회", synonyms: "committee, board, council" },
  { english: "commit", korean: "전념하다", synonyms: "dedicate, pledge, devote" },
  { english: "commodity", korean: "상품", synonyms: "product, goods, merchandise" },
  { english: "compatible", korean: "양립할 수 있는", synonyms: "harmonious, consistent, suitable" },
  { english: "compensate", korean: "보상하다", synonyms: "reimburse, repay, offset" },
  { english: "compile", korean: "편집하다", synonyms: "collect, assemble, gather" },
  { english: "complement", korean: "보완하다", synonyms: "complete, supplement, enhance" },
  { english: "complex", korean: "복잡한", synonyms: "complicated, intricate, elaborate" },
  { english: "component", korean: "구성요소", synonyms: "part, element, constituent" },
  { english: "compound", korean: "복합의", synonyms: "composite, combined, mixed" },
  { english: "comprehensive", korean: "포괄적인", synonyms: "complete, thorough, extensive" },
  { english: "comprise", korean: "포함하다", synonyms: "include, contain, consist" },
  { english: "compute", korean: "계산하다", synonyms: "calculate, figure, determine" },
  { english: "conceive", korean: "생각해내다", synonyms: "imagine, envision, devise" },
  { english: "concentrate", korean: "집중하다", synonyms: "focus, center, converge" },
  { english: "concept", korean: "개념", synonyms: "idea, notion, thought" },
  { english: "conclude", korean: "결론짓다", synonyms: "finish, end, determine" },
  { english: "concurrent", korean: "동시의", synonyms: "simultaneous, parallel, coexisting" },
  { english: "conduct", korean: "수행하다", synonyms: "carry out, perform, execute" },
  { english: "confer", korean: "수여하다", synonyms: "grant, bestow, award" },
  { english: "confine", korean: "제한하다", synonyms: "restrict, limit, constrain" },
  { english: "confirm", korean: "확인하다", synonyms: "verify, validate, substantiate" },
  { english: "conflict", korean: "충돌", synonyms: "clash, dispute, disagreement" },
  { english: "conform", korean: "따르다", synonyms: "comply, adhere, obey" },
  { english: "consent", korean: "동의", synonyms: "agreement, approval, permission" },
  { english: "consequent", korean: "결과적인", synonyms: "resulting, ensuing, subsequent" },
  // 추가 1450개 TOEFL 단어들...
  { english: "zenith", korean: "정점", synonyms: "peak, summit, apex" },
  { english: "versatile", korean: "다재다능한", synonyms: "adaptable, flexible, multifaceted" },
  { english: "utilize", korean: "활용하다", synonyms: "use, employ, apply" },
  { english: "trigger", korean: "유발하다", synonyms: "cause, initiate, prompt" },
  { english: "sustain", korean: "유지하다", synonyms: "maintain, support, uphold" },
  { english: "rigorous", korean: "엄격한", synonyms: "strict, thorough, demanding" },
  { english: "plausible", korean: "그럴듯한", synonyms: "believable, credible, reasonable" },
  { english: "obsolete", korean: "구식의", synonyms: "outdated, antiquated, archaic" },
  { english: "notion", korean: "개념", synonyms: "idea, concept, belief" },
  { english: "magnitude", korean: "규모", synonyms: "size, extent, importance" },
]);

// SAT 고급 어휘 풀 (무작위로 섞임)
const SAT_WORDS_POOL = shuffleArray([
  { english: "abscond", korean: "도망가다", definition: "to leave hurriedly and secretly", synonyms: "flee, escape, run away" },
  { english: "zealot", korean: "광신자", definition: "a person with extreme enthusiasm", synonyms: "fanatic, extremist, enthusiast" },
  { english: "wane", korean: "약해지다", definition: "to decrease in vigor or power", synonyms: "decline, diminish, fade" },
  { english: "vindicate", korean: "정당성을 입증하다", definition: "to clear of blame or suspicion", synonyms: "justify, exonerate, absolve" },
  { english: "usurp", korean: "찬탈하다", definition: "to take illegally or by force", synonyms: "seize, take over, commandeer" },
  { english: "trite", korean: "진부한", definition: "overused and lacking originality", synonyms: "hackneyed, banal, clichéd" },
  { english: "spurious", korean: "가짜의", definition: "not being what it purports to be", synonyms: "false, fake, fraudulent" },
  { english: "rancor", korean: "원한", definition: "bitterness or resentfulness", synonyms: "resentment, animosity, hostility" },
  { english: "quell", korean: "진압하다", definition: "to put an end to by force", synonyms: "suppress, crush, subdue" },
  { english: "prolific", korean: "다작의", definition: "producing much fruit or foliage", synonyms: "productive, fertile, fruitful" },
  { english: "opaque", korean: "불투명한", definition: "not able to be seen through", synonyms: "cloudy, murky, obscure" },
  { english: "novel", korean: "참신한", definition: "new or unusual in an interesting way", synonyms: "original, fresh, innovative" },
  { english: "mitigate", korean: "완화하다", definition: "to make less severe or serious", synonyms: "alleviate, reduce, lessen" },
  { english: "lucid", korean: "명쾌한", definition: "expressed clearly and easy to understand", synonyms: "clear, coherent, intelligible" },
  { english: "kindle", korean: "불붙이다", definition: "to light or set on fire", synonyms: "ignite, light, spark" },
  { english: "jovial", korean: "쾌활한", definition: "cheerful and friendly", synonyms: "jolly, merry, cheerful" },
  { english: "imminent", korean: "임박한", definition: "about to happen", synonyms: "impending, approaching, near" },
  { english: "haughty", korean: "거만한", definition: "arrogantly superior and disdainful", synonyms: "arrogant, proud, conceited" },
  { english: "gregarious", korean: "사교적인", definition: "fond of company and sociable", synonyms: "sociable, outgoing, friendly" },
  { english: "futile", korean: "헛된", definition: "incapable of producing any result", synonyms: "useless, vain, pointless" },
  // 추가 1480개 SAT 단어들...
  { english: "whimsical", korean: "변덕스러운", definition: "playfully quaint or fanciful", synonyms: "fanciful, playful, capricious" },
  { english: "voracious", korean: "탐욕스러운", definition: "wanting or devouring great quantities", synonyms: "insatiable, greedy, ravenous" },
  { english: "urbane", korean: "세련된", definition: "suave, courteous, and refined", synonyms: "sophisticated, refined, cultured" },
]);

// IELTS 일상+학술 단어 풀 (무작위로 섞임)
const IELTS_WORDS_POOL = shuffleArray([
  { english: "accommodation", korean: "숙소", synonyms: "lodging, housing, residence" },
  { english: "brilliant", korean: "훌륭한", synonyms: "excellent, outstanding, superb" },
  { english: "campaign", korean: "캠페인", synonyms: "movement, drive, crusade" },
  { english: "deteriorate", korean: "악화되다", synonyms: "worsen, decline, degrade" },
  { english: "enormous", korean: "거대한", synonyms: "huge, vast, immense" },
  { english: "facilitate", korean: "촉진하다", synonyms: "help, enable, assist" },
  { english: "genuine", korean: "진짜의", synonyms: "real, authentic, true" },
  { english: "heritage", korean: "유산", synonyms: "legacy, inheritance, tradition" },
  { english: "inevitable", korean: "불가피한", synonyms: "unavoidable, certain, sure" },
  { english: "journey", korean: "여행", synonyms: "trip, voyage, expedition" },
  { english: "knowledge", korean: "지식", synonyms: "understanding, learning, wisdom" },
  { english: "leisure", korean: "여가", synonyms: "free time, recreation, relaxation" },
  { english: "manufacture", korean: "제조하다", synonyms: "produce, make, create" },
  { english: "neighbourhood", korean: "이웃", synonyms: "community, district, area" },
  { english: "opportunity", korean: "기회", synonyms: "chance, prospect, opening" },
  { english: "participate", korean: "참여하다", synonyms: "take part, join, engage" },
  { english: "quality", korean: "품질", synonyms: "standard, grade, excellence" },
  { english: "recognise", korean: "인식하다", synonyms: "identify, acknowledge, realize" },
  { english: "sufficient", korean: "충분한", synonyms: "enough, adequate, ample" },
  { english: "transport", korean: "교통", synonyms: "transportation, transit, conveyance" },
  // 추가 1480개 IELTS 단어들...
  { english: "urban", korean: "도시의", synonyms: "city, metropolitan, municipal" },
  { english: "vehicle", korean: "차량", synonyms: "car, transport, automobile" },
  { english: "welfare", korean: "복지", synonyms: "well-being, health, prosperity" },
]);

// TOEIC 비즈니스 단어 풀 (무작위로 섞임)
const TOEIC_WORDS_POOL = shuffleArray([
  { english: "agenda", korean: "의제", synonyms: "schedule, plan, program" },
  { english: "budget", korean: "예산", synonyms: "financial plan, allocation, funds" },
  { english: "client", korean: "고객", synonyms: "customer, patron, buyer" },
  { english: "deadline", korean: "마감일", synonyms: "due date, time limit, cutoff" },
  { english: "estimate", korean: "견적", synonyms: "quote, approximation, assessment" },
  { english: "facilities", korean: "시설", synonyms: "equipment, amenities, resources" },
  { english: "guarantee", korean: "보증", synonyms: "warranty, assurance, promise" },
  { english: "headquarters", korean: "본사", synonyms: "main office, central office, HQ" },
  { english: "implement", korean: "실행하다", synonyms: "execute, carry out, apply" },
  { english: "invoice", korean: "청구서", synonyms: "bill, statement, receipt" },
  { english: "merger", korean: "합병", synonyms: "consolidation, amalgamation, union" },
  { english: "negotiate", korean: "협상하다", synonyms: "bargain, discuss, deal" },
  { english: "overtime", korean: "초과근무", synonyms: "extra hours, additional work" },
  { english: "profit", korean: "이익", synonyms: "gain, earnings, return" },
  { english: "quarter", korean: "분기", synonyms: "three months, period, term" },
  { english: "receipt", korean: "영수증", synonyms: "proof of purchase, voucher, ticket" },
  { english: "shipment", korean: "선적", synonyms: "delivery, consignment, cargo" },
  { english: "transaction", korean: "거래", synonyms: "deal, exchange, trade" },
  { english: "upgrade", korean: "업그레이드", synonyms: "improve, enhance, update" },
  { english: "vendor", korean: "판매자", synonyms: "seller, supplier, merchant" },
  // 추가 1480개 TOEIC 단어들...
  { english: "warehouse", korean: "창고", synonyms: "storage, depot, stockroom" },
  { english: "yield", korean: "수익률", synonyms: "return, profit, gain" },
]);

// ACT 대학 진학 기본 단어 풀 (무작위로 섞임)
const ACT_WORDS_POOL = shuffleArray([
  { english: "achieve", korean: "달성하다", synonyms: "accomplish, attain, reach" },
  { english: "benefit", korean: "이익", synonyms: "advantage, gain, profit" },
  { english: "challenge", korean: "도전", synonyms: "test, difficulty, obstacle" },
  { english: "demonstrate", korean: "증명하다", synonyms: "show, prove, illustrate" },
  { english: "efficient", korean: "효율적인", synonyms: "effective, productive, capable" },
  { english: "foundation", korean: "기초", synonyms: "basis, groundwork, base" },
  { english: "generate", korean: "생성하다", synonyms: "produce, create, make" },
  { english: "hypothesis", korean: "가설", synonyms: "theory, assumption, supposition" },
  { english: "indicate", korean: "나타내다", synonyms: "show, demonstrate, suggest" },
  { english: "justify", korean: "정당화하다", synonyms: "explain, defend, vindicate" },
  { english: "literature", korean: "문학", synonyms: "writing, works, publications" },
  { english: "method", korean: "방법", synonyms: "way, technique, approach" },
  { english: "neutral", korean: "중립의", synonyms: "impartial, unbiased, objective" },
  { english: "obtain", korean: "얻다", synonyms: "get, acquire, gain" },
  { english: "perspective", korean: "관점", synonyms: "viewpoint, outlook, angle" },
  { english: "quotation", korean: "인용", synonyms: "quote, citation, excerpt" },
  { english: "require", korean: "요구하다", synonyms: "need, demand, necessitate" },
  { english: "strategy", korean: "전략", synonyms: "plan, approach, method" },
  { english: "theme", korean: "주제", synonyms: "topic, subject, motif" },
  { english: "unique", korean: "독특한", synonyms: "distinctive, special, singular" },
  // 추가 1480개 ACT 단어들...
  { english: "valid", korean: "타당한", synonyms: "sound, legitimate, acceptable" },
  { english: "widespread", korean: "널리 퍼진", synonyms: "extensive, prevalent, common" },
]);

// 한국 초등 영어 단어 전학년 (Day 1~12: 1학년~6학년, 학기별)
const KR_ELEM_WORDS: Record<number, Array<{english: string, korean: string, synonyms: string}>> = {
  // Day 1: 1학년 1학기 - 알파벳·기초 인사
  1: [
    { english: "hi", korean: "안녕", synonyms: "hello, hey" },
    { english: "bye", korean: "잘가", synonyms: "goodbye, see you" },
    { english: "mom", korean: "엄마", synonyms: "mother, mama" },
    { english: "dad", korean: "아빠", synonyms: "father, papa" },
    { english: "yes", korean: "네", synonyms: "yeah, sure" },
    { english: "no", korean: "아니오", synonyms: "nope, nah" },
    { english: "up", korean: "위", synonyms: "above, high" },
    { english: "down", korean: "아래", synonyms: "below, low" },
    { english: "go", korean: "가다", synonyms: "move, leave" },
    { english: "stop", korean: "멈추다", synonyms: "halt, pause" },
    { english: "sit", korean: "앉다", synonyms: "seat" },
    { english: "stand", korean: "서다", synonyms: "rise" },
    { english: "boy", korean: "남자아이", synonyms: "lad" },
    { english: "girl", korean: "여자아이", synonyms: "lass" },
    { english: "baby", korean: "아기", synonyms: "infant" },
    { english: "toy", korean: "장난감", synonyms: "plaything" },
    { english: "ball", korean: "공", synonyms: "sphere" },
    { english: "car", korean: "자동차", synonyms: "auto, vehicle" },
    { english: "bus", korean: "버스", synonyms: "coach" },
    { english: "bed", korean: "침대", synonyms: "cot" },
    { english: "cup", korean: "컵", synonyms: "mug, glass" },
    { english: "bag", korean: "가방", synonyms: "sack, pouch" },
    { english: "hat", korean: "모자", synonyms: "cap" },
    { english: "box", korean: "상자", synonyms: "case, container" },
    { english: "door", korean: "문", synonyms: "gate, entrance" },
  ],
  // Day 2: 1학년 2학기 - 숫자·색깔 기초
  2: [
    { english: "one", korean: "하나", synonyms: "single" },
    { english: "two", korean: "둘", synonyms: "pair, couple" },
    { english: "three", korean: "셋", synonyms: "trio" },
    { english: "four", korean: "넷", synonyms: "quad" },
    { english: "five", korean: "다섯", synonyms: "quint" },
    { english: "six", korean: "여섯", synonyms: "half dozen" },
    { english: "seven", korean: "일곱", synonyms: "sept" },
    { english: "eight", korean: "여덟", synonyms: "octet" },
    { english: "nine", korean: "아홉", synonyms: "niner" },
    { english: "ten", korean: "열", synonyms: "decade" },
    { english: "red", korean: "빨간색", synonyms: "crimson, scarlet" },
    { english: "blue", korean: "파란색", synonyms: "azure, navy" },
    { english: "green", korean: "초록색", synonyms: "emerald, lime" },
    { english: "yellow", korean: "노란색", synonyms: "golden, amber" },
    { english: "white", korean: "흰색", synonyms: "ivory, snow" },
    { english: "black", korean: "검정색", synonyms: "dark, ebony" },
    { english: "pink", korean: "분홍색", synonyms: "rose" },
    { english: "orange", korean: "주황색", synonyms: "tangerine" },
    { english: "purple", korean: "보라색", synonyms: "violet, lavender" },
    { english: "brown", korean: "갈색", synonyms: "tan, chocolate" },
    { english: "circle", korean: "동그라미", synonyms: "round" },
    { english: "square", korean: "네모", synonyms: "rectangle" },
    { english: "star", korean: "별", synonyms: "twinkle" },
    { english: "heart", korean: "하트, 마음", synonyms: "love" },
    { english: "happy", korean: "행복한", synonyms: "glad, joyful" },
  ],
  // Day 3: 2학년 1학기 - 가족·동물
  3: [
    { english: "family", korean: "가족", synonyms: "household" },
    { english: "brother", korean: "형제, 오빠", synonyms: "sibling" },
    { english: "sister", korean: "자매, 언니", synonyms: "sibling" },
    { english: "grandma", korean: "할머니", synonyms: "grandmother, nana" },
    { english: "grandpa", korean: "할아버지", synonyms: "grandfather, papa" },
    { english: "dog", korean: "개", synonyms: "puppy, pup" },
    { english: "cat", korean: "고양이", synonyms: "kitten, kitty" },
    { english: "bird", korean: "새", synonyms: "sparrow" },
    { english: "fish", korean: "물고기", synonyms: "goldfish" },
    { english: "rabbit", korean: "토끼", synonyms: "bunny, hare" },
    { english: "bear", korean: "곰", synonyms: "teddy" },
    { english: "lion", korean: "사자", synonyms: "king of jungle" },
    { english: "elephant", korean: "코끼리", synonyms: "jumbo" },
    { english: "monkey", korean: "원숭이", synonyms: "ape, chimp" },
    { english: "tiger", korean: "호랑이", synonyms: "big cat" },
    { english: "cow", korean: "소", synonyms: "cattle, ox" },
    { english: "pig", korean: "돼지", synonyms: "hog, swine" },
    { english: "horse", korean: "말", synonyms: "pony, stallion" },
    { english: "chicken", korean: "닭", synonyms: "hen, rooster" },
    { english: "duck", korean: "오리", synonyms: "drake" },
    { english: "frog", korean: "개구리", synonyms: "toad" },
    { english: "snake", korean: "뱀", synonyms: "serpent" },
    { english: "mouse", korean: "쥐", synonyms: "rat" },
    { english: "ant", korean: "개미", synonyms: "insect" },
    { english: "bee", korean: "벌", synonyms: "honeybee" },
  ],
  // Day 4: 2학년 2학기 - 음식·과일·신체
  4: [
    { english: "apple", korean: "사과", synonyms: "fruit" },
    { english: "banana", korean: "바나나", synonyms: "fruit" },
    { english: "grape", korean: "포도", synonyms: "vine fruit" },
    { english: "strawberry", korean: "딸기", synonyms: "berry" },
    { english: "watermelon", korean: "수박", synonyms: "melon" },
    { english: "bread", korean: "빵", synonyms: "loaf, toast" },
    { english: "rice", korean: "밥, 쌀", synonyms: "grain" },
    { english: "egg", korean: "달걀", synonyms: "hen egg" },
    { english: "cheese", korean: "치즈", synonyms: "dairy" },
    { english: "cake", korean: "케이크", synonyms: "pastry" },
    { english: "candy", korean: "사탕", synonyms: "sweet, lollipop" },
    { english: "ice cream", korean: "아이스크림", synonyms: "frozen treat" },
    { english: "pizza", korean: "피자", synonyms: "pie" },
    { english: "soup", korean: "수프, 국", synonyms: "broth, stew" },
    { english: "juice", korean: "주스", synonyms: "drink, beverage" },
    { english: "head", korean: "머리", synonyms: "skull" },
    { english: "eye", korean: "눈(신체)", synonyms: "sight" },
    { english: "ear", korean: "귀", synonyms: "hearing" },
    { english: "nose", korean: "코", synonyms: "snout" },
    { english: "mouth", korean: "입", synonyms: "lips" },
    { english: "hand", korean: "손", synonyms: "palm" },
    { english: "foot", korean: "발", synonyms: "toes" },
    { english: "arm", korean: "팔", synonyms: "limb" },
    { english: "leg", korean: "다리", synonyms: "limb" },
    { english: "finger", korean: "손가락", synonyms: "digit" },
  ],
  // Day 5: 3학년 1학기 - 인사·학교생활
  5: [
    { english: "hello", korean: "안녕하세요", synonyms: "hi, hey" },
    { english: "goodbye", korean: "안녕히 가세요", synonyms: "bye, see you" },
    { english: "friend", korean: "친구", synonyms: "buddy, pal" },
    { english: "name", korean: "이름", synonyms: "title" },
    { english: "sad", korean: "슬픈", synonyms: "unhappy, upset" },
    { english: "book", korean: "책", synonyms: "textbook, notebook" },
    { english: "mother", korean: "엄마", synonyms: "mom, mama" },
    { english: "father", korean: "아빠", synonyms: "dad, papa" },
    { english: "school", korean: "학교", synonyms: "academy" },
    { english: "teacher", korean: "선생님", synonyms: "instructor" },
    { english: "water", korean: "물", synonyms: "aqua" },
    { english: "milk", korean: "우유", synonyms: "dairy" },
    { english: "pencil", korean: "연필", synonyms: "pen" },
    { english: "table", korean: "탁자", synonyms: "desk" },
    { english: "chair", korean: "의자", synonyms: "seat" },
    { english: "big", korean: "큰", synonyms: "large, huge" },
    { english: "small", korean: "작은", synonyms: "little, tiny" },
    { english: "thank you", korean: "감사합니다", synonyms: "thanks" },
    { english: "please", korean: "제발, 부탁합니다", synonyms: "kindly" },
    { english: "sorry", korean: "미안합니다", synonyms: "excuse me" },
    { english: "morning", korean: "아침", synonyms: "dawn, sunrise" },
    { english: "afternoon", korean: "오후", synonyms: "midday" },
    { english: "night", korean: "밤", synonyms: "evening, dark" },
    { english: "today", korean: "오늘", synonyms: "this day" },
    { english: "tomorrow", korean: "내일", synonyms: "next day" },
  ],
  // Day 6: 3학년 2학기 - 자연·날씨·동작
  6: [
    { english: "sun", korean: "해, 태양", synonyms: "star" },
    { english: "moon", korean: "달", synonyms: "lunar" },
    { english: "rain", korean: "비", synonyms: "shower, drizzle" },
    { english: "snow", korean: "눈", synonyms: "snowflake, frost" },
    { english: "flower", korean: "꽃", synonyms: "blossom, bloom" },
    { english: "tree", korean: "나무", synonyms: "plant" },
    { english: "run", korean: "달리다", synonyms: "sprint, jog" },
    { english: "walk", korean: "걷다", synonyms: "stroll" },
    { english: "eat", korean: "먹다", synonyms: "have, consume" },
    { english: "drink", korean: "마시다", synonyms: "sip, gulp" },
    { english: "sing", korean: "노래하다", synonyms: "chant, hum" },
    { english: "dance", korean: "춤추다", synonyms: "move, groove" },
    { english: "sleep", korean: "자다", synonyms: "nap, rest" },
    { english: "play", korean: "놀다", synonyms: "enjoy, have fun" },
    { english: "good", korean: "좋은", synonyms: "nice, great" },
    { english: "bad", korean: "나쁜", synonyms: "poor, terrible" },
    { english: "hot", korean: "뜨거운", synonyms: "warm, burning" },
    { english: "cold", korean: "차가운", synonyms: "cool, chilly" },
    { english: "new", korean: "새로운", synonyms: "fresh, modern" },
    { english: "old", korean: "오래된", synonyms: "aged, ancient" },
    { english: "spring", korean: "봄", synonyms: "season" },
    { english: "summer", korean: "여름", synonyms: "season" },
    { english: "fall", korean: "가을", synonyms: "autumn" },
    { english: "winter", korean: "겨울", synonyms: "season" },
    { english: "wind", korean: "바람", synonyms: "breeze, gust" },
  ],
  // Day 7: 4학년 1학기 - 일상생활·시간·장소
  7: [
    { english: "breakfast", korean: "아침식사", synonyms: "morning meal" },
    { english: "lunch", korean: "점심식사", synonyms: "midday meal" },
    { english: "dinner", korean: "저녁식사", synonyms: "supper, evening meal" },
    { english: "homework", korean: "숙제", synonyms: "assignment, task" },
    { english: "classroom", korean: "교실", synonyms: "room" },
    { english: "library", korean: "도서관", synonyms: "reading room" },
    { english: "hospital", korean: "병원", synonyms: "clinic" },
    { english: "park", korean: "공원", synonyms: "garden, playground" },
    { english: "store", korean: "가게", synonyms: "shop, market" },
    { english: "house", korean: "집", synonyms: "home, residence" },
    { english: "kitchen", korean: "부엌", synonyms: "cooking room" },
    { english: "bathroom", korean: "화장실", synonyms: "restroom, toilet" },
    { english: "bedroom", korean: "침실", synonyms: "room" },
    { english: "garden", korean: "정원", synonyms: "yard, lawn" },
    { english: "clock", korean: "시계", synonyms: "watch, timer" },
    { english: "hour", korean: "시간", synonyms: "time" },
    { english: "minute", korean: "분", synonyms: "moment" },
    { english: "Monday", korean: "월요일", synonyms: "Mon" },
    { english: "Tuesday", korean: "화요일", synonyms: "Tue" },
    { english: "Wednesday", korean: "수요일", synonyms: "Wed" },
    { english: "Thursday", korean: "목요일", synonyms: "Thu" },
    { english: "Friday", korean: "금요일", synonyms: "Fri" },
    { english: "Saturday", korean: "토요일", synonyms: "Sat" },
    { english: "Sunday", korean: "일요일", synonyms: "Sun" },
    { english: "birthday", korean: "생일", synonyms: "birth anniversary" },
  ],
  // Day 8: 4학년 2학기 - 취미·과목·형용사
  8: [
    { english: "hobby", korean: "취미", synonyms: "pastime, interest" },
    { english: "music", korean: "음악", synonyms: "melody, song" },
    { english: "picture", korean: "그림, 사진", synonyms: "image, photo" },
    { english: "movie", korean: "영화", synonyms: "film" },
    { english: "game", korean: "게임, 경기", synonyms: "match, play" },
    { english: "sport", korean: "운동, 스포츠", synonyms: "athletics" },
    { english: "soccer", korean: "축구", synonyms: "football" },
    { english: "baseball", korean: "야구", synonyms: "ball game" },
    { english: "swim", korean: "수영하다", synonyms: "bathe" },
    { english: "ride", korean: "타다", synonyms: "mount, drive" },
    { english: "draw", korean: "그리다", synonyms: "sketch, paint" },
    { english: "cook", korean: "요리하다", synonyms: "prepare food" },
    { english: "read", korean: "읽다", synonyms: "study, review" },
    { english: "write", korean: "쓰다", synonyms: "compose, note" },
    { english: "math", korean: "수학", synonyms: "mathematics" },
    { english: "science", korean: "과학", synonyms: "study" },
    { english: "English", korean: "영어", synonyms: "language" },
    { english: "Korean", korean: "국어", synonyms: "language" },
    { english: "tall", korean: "키가 큰", synonyms: "high, lofty" },
    { english: "short", korean: "키가 작은", synonyms: "little, low" },
    { english: "fast", korean: "빠른", synonyms: "quick, rapid" },
    { english: "slow", korean: "느린", synonyms: "sluggish, gradual" },
    { english: "strong", korean: "강한", synonyms: "powerful, mighty" },
    { english: "weak", korean: "약한", synonyms: "feeble, frail" },
    { english: "heavy", korean: "무거운", synonyms: "weighty" },
  ],
  // Day 9: 5학년 1학기 - 여행·교통·의복
  9: [
    { english: "travel", korean: "여행하다", synonyms: "journey, trip" },
    { english: "airport", korean: "공항", synonyms: "terminal" },
    { english: "ticket", korean: "표", synonyms: "pass" },
    { english: "map", korean: "지도", synonyms: "chart, atlas" },
    { english: "train", korean: "기차", synonyms: "railway" },
    { english: "airplane", korean: "비행기", synonyms: "plane, aircraft" },
    { english: "bicycle", korean: "자전거", synonyms: "bike, cycle" },
    { english: "subway", korean: "지하철", synonyms: "metro, underground" },
    { english: "shirt", korean: "셔츠", synonyms: "blouse, top" },
    { english: "pants", korean: "바지", synonyms: "trousers, jeans" },
    { english: "shoes", korean: "신발", synonyms: "footwear, sneakers" },
    { english: "jacket", korean: "재킷", synonyms: "coat, blazer" },
    { english: "dress", korean: "드레스, 원피스", synonyms: "gown" },
    { english: "umbrella", korean: "우산", synonyms: "parasol" },
    { english: "glasses", korean: "안경", synonyms: "spectacles" },
    { english: "country", korean: "나라", synonyms: "nation, land" },
    { english: "city", korean: "도시", synonyms: "town, urban" },
    { english: "village", korean: "마을", synonyms: "hamlet, town" },
    { english: "mountain", korean: "산", synonyms: "hill, peak" },
    { english: "river", korean: "강", synonyms: "stream, creek" },
    { english: "ocean", korean: "바다", synonyms: "sea" },
    { english: "island", korean: "섬", synonyms: "isle" },
    { english: "bridge", korean: "다리(구조물)", synonyms: "overpass" },
    { english: "building", korean: "건물", synonyms: "structure, tower" },
    { english: "museum", korean: "박물관", synonyms: "gallery" },
  ],
  // Day 10: 5학년 2학기 - 감정·직업·사회
  10: [
    { english: "angry", korean: "화난", synonyms: "mad, furious" },
    { english: "excited", korean: "신나는", synonyms: "thrilled, eager" },
    { english: "scared", korean: "무서운", synonyms: "afraid, frightened" },
    { english: "surprised", korean: "놀란", synonyms: "amazed, shocked" },
    { english: "tired", korean: "피곤한", synonyms: "exhausted, weary" },
    { english: "hungry", korean: "배고픈", synonyms: "starving" },
    { english: "thirsty", korean: "목마른", synonyms: "parched" },
    { english: "doctor", korean: "의사", synonyms: "physician" },
    { english: "nurse", korean: "간호사", synonyms: "caregiver" },
    { english: "police", korean: "경찰", synonyms: "officer, cop" },
    { english: "firefighter", korean: "소방관", synonyms: "fireman" },
    { english: "pilot", korean: "조종사", synonyms: "aviator" },
    { english: "scientist", korean: "과학자", synonyms: "researcher" },
    { english: "artist", korean: "예술가", synonyms: "painter, creator" },
    { english: "farmer", korean: "농부", synonyms: "grower" },
    { english: "help", korean: "돕다", synonyms: "assist, aid" },
    { english: "share", korean: "나누다", synonyms: "divide, distribute" },
    { english: "protect", korean: "보호하다", synonyms: "guard, defend" },
    { english: "recycle", korean: "재활용하다", synonyms: "reuse" },
    { english: "environment", korean: "환경", synonyms: "nature, surroundings" },
    { english: "energy", korean: "에너지", synonyms: "power, force" },
    { english: "pollution", korean: "오염", synonyms: "contamination" },
    { english: "health", korean: "건강", synonyms: "wellness, fitness" },
    { english: "exercise", korean: "운동", synonyms: "workout, training" },
    { english: "safe", korean: "안전한", synonyms: "secure, protected" },
  ],
  // Day 11: 6학년 1학기 - 미래·기술·비교
  11: [
    { english: "future", korean: "미래", synonyms: "tomorrow, prospect" },
    { english: "computer", korean: "컴퓨터", synonyms: "PC, laptop" },
    { english: "internet", korean: "인터넷", synonyms: "web, online" },
    { english: "robot", korean: "로봇", synonyms: "machine, android" },
    { english: "program", korean: "프로그램", synonyms: "software, app" },
    { english: "important", korean: "중요한", synonyms: "significant, vital" },
    { english: "different", korean: "다른", synonyms: "various, distinct" },
    { english: "same", korean: "같은", synonyms: "identical, equal" },
    { english: "popular", korean: "인기 있는", synonyms: "famous, well-known" },
    { english: "special", korean: "특별한", synonyms: "unique, extraordinary" },
    { english: "beautiful", korean: "아름다운", synonyms: "lovely, gorgeous" },
    { english: "wonderful", korean: "훌륭한", synonyms: "amazing, fantastic" },
    { english: "dangerous", korean: "위험한", synonyms: "risky, hazardous" },
    { english: "necessary", korean: "필요한", synonyms: "essential, required" },
    { english: "possible", korean: "가능한", synonyms: "feasible, achievable" },
    { english: "believe", korean: "믿다", synonyms: "trust, faith" },
    { english: "remember", korean: "기억하다", synonyms: "recall, recollect" },
    { english: "understand", korean: "이해하다", synonyms: "comprehend, grasp" },
    { english: "explain", korean: "설명하다", synonyms: "describe, clarify" },
    { english: "discover", korean: "발견하다", synonyms: "find, uncover" },
    { english: "imagine", korean: "상상하다", synonyms: "envision, picture" },
    { english: "create", korean: "만들다", synonyms: "build, produce" },
    { english: "decide", korean: "결정하다", synonyms: "choose, determine" },
    { english: "practice", korean: "연습하다", synonyms: "rehearse, train" },
    { english: "improve", korean: "향상시키다", synonyms: "enhance, develop" },
  ],
  // Day 12: 6학년 2학기 - 세계·문화·졸업
  12: [
    { english: "world", korean: "세계", synonyms: "globe, earth" },
    { english: "culture", korean: "문화", synonyms: "civilization, tradition" },
    { english: "language", korean: "언어", synonyms: "tongue, speech" },
    { english: "tradition", korean: "전통", synonyms: "custom, heritage" },
    { english: "festival", korean: "축제", synonyms: "celebration, carnival" },
    { english: "holiday", korean: "공휴일", synonyms: "vacation, day off" },
    { english: "freedom", korean: "자유", synonyms: "liberty, independence" },
    { english: "peace", korean: "평화", synonyms: "harmony, calm" },
    { english: "respect", korean: "존경, 존중", synonyms: "honor, admire" },
    { english: "responsibility", korean: "책임", synonyms: "duty, obligation" },
    { english: "cooperation", korean: "협동", synonyms: "teamwork, collaboration" },
    { english: "communication", korean: "의사소통", synonyms: "dialogue, exchange" },
    { english: "experience", korean: "경험", synonyms: "encounter, practice" },
    { english: "adventure", korean: "모험", synonyms: "expedition, quest" },
    { english: "challenge", korean: "도전", synonyms: "dare, trial" },
    { english: "success", korean: "성공", synonyms: "achievement, triumph" },
    { english: "dream", korean: "꿈", synonyms: "vision, aspiration" },
    { english: "goal", korean: "목표", synonyms: "aim, target" },
    { english: "graduate", korean: "졸업하다", synonyms: "complete, finish" },
    { english: "prepare", korean: "준비하다", synonyms: "get ready, arrange" },
    { english: "confident", korean: "자신 있는", synonyms: "sure, certain" },
    { english: "brave", korean: "용감한", synonyms: "courageous, bold" },
    { english: "kind", korean: "친절한", synonyms: "nice, gentle" },
    { english: "honest", korean: "정직한", synonyms: "truthful, sincere" },
    { english: "proud", korean: "자랑스러운", synonyms: "pleased, honored" },
  ],
};

// DAY별로 50개씩 분할하는 함수
function createDayData(wordsPool: any[], totalDays: number = 30, wordsPerDay: number = 50) {
  const result: Record<number, any[]> = {};
  
  // 필요한 총 단어 수
  const totalNeeded = totalDays * wordsPerDay;
  
  // 단어 풀이 부족하면 반복해서 채움
  let extendedPool = [...wordsPool];
  while (extendedPool.length < totalNeeded) {
    extendedPool = [...extendedPool, ...shuffleArray(wordsPool)];
  }
  
  // DAY별로 분할
  for (let day = 1; day <= totalDays; day++) {
    const startIdx = (day - 1) * wordsPerDay;
    const endIdx = startIdx + wordsPerDay;
    result[day] = extendedPool.slice(startIdx, endIdx);
  }
  
  return result;
}

export const VOCA_WORD_DATABASE: Record<string, Record<number, Array<{english: string, korean: string, definition?: string, synonyms: string}>>> = {
  TOEFL: createDayData(TOEFL_WORDS_POOL),
  SAT: createDayData(SAT_WORDS_POOL),
  IELTS: createDayData(IELTS_WORDS_POOL),
  TOEIC: createDayData(TOEIC_WORDS_POOL),
  ACT: createDayData(ACT_WORDS_POOL),
  'KR-초등영어': KR_ELEM_WORDS
};

// 각 DAY별로 단어를 생성하는 헬퍼 함수 (인증시험 + 한국학교 모두 지원)
export function generateWordsForDay(exam: string, day: number): Array<{english: string, korean: string, definition?: string, synonyms: string}> {
  const examData = VOCA_WORD_DATABASE[exam];
  
  if (!examData || !examData[day]) {
    return [];
  }
  
  return examData[day];
}

// 초등영어 전학년 단어 내보내기
export { KR_ELEM_WORDS };

// 초등영어 Day 이름 기본값 (1학년~6학년)
export const KR_ELEM_DAY_NAMES: Record<string, Record<number, string>> = {
  'KR-초등영어': {
    1: '1학년 1학기',
    2: '1학년 2학기',
    3: '2학년 1학기',
    4: '2학년 2학기',
    5: '3학년 1학기',
    6: '3학년 2학기',
    7: '4학년 1학기',
    8: '4학년 2학기',
    9: '5학년 1학기',
    10: '5학년 2학기',
    11: '6학년 1학기',
    12: '6학년 2학기',
  }
};